id: IE681C7B5
legacy_id: P009519
ocr_import_info:
  bdrc_scan_id: W28942
  source: bdrc
  ocr_info:
    timestamp: '2021-01-21T18:46:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:20:00.070314+00:00'
last_modified: 2022-09-02 17:21:43.095072
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28942
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28942
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཤེས་བྱ་ཀུན་རིག
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
statistics: null
quality: null
bases:
  I4882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4882
      total_pages: 912
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4882.txt
    legacy_id: v005
  I4883:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4883
      total_pages: 936
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4883.txt
    legacy_id: v006
  I4884:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4884
      total_pages: 854
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4884.txt
    legacy_id: v007
  I4885:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4885
      total_pages: 679
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4885.txt
    legacy_id: v008
  I4878:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4878
      total_pages: 846
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4878.txt
    legacy_id: v001
  I4879:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4879
      total_pages: 984
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4879.txt
    legacy_id: v002
  I4880:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4880
      total_pages: 774
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4880.txt
    legacy_id: v003
  I4887:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4887
      total_pages: 732
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4887.txt
    legacy_id: v010
  I4886:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4886
      total_pages: 840
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4886.txt
    legacy_id: v009
  I4881:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4881
      total_pages: 888
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4881.txt
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
