id: IE681C7B5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:35:18+00:00'
last_modified: '2022-06-08T11:36:25.278277+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28942
  title: གསུང་འབུམ། ཤེས་བྱ་ཀུན་རིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6F97:
      image_group_id: I4878
      title: ''
      total_pages: 846
      order: 1
      base_file: 6F97.txt
    258C:
      image_group_id: I4879
      title: ''
      total_pages: 984
      order: 2
      base_file: 258C.txt
    9D19:
      image_group_id: I4880
      title: ''
      total_pages: 774
      order: 3
      base_file: 9D19.txt
    B7E6:
      image_group_id: I4881
      title: ''
      total_pages: 888
      order: 4
      base_file: B7E6.txt
    428F:
      image_group_id: I4882
      title: ''
      total_pages: 912
      order: 5
      base_file: 428F.txt
    A093:
      image_group_id: I4883
      title: ''
      total_pages: 936
      order: 6
      base_file: A093.txt
    C4F1:
      image_group_id: I4884
      title: ''
      total_pages: 854
      order: 7
      base_file: C4F1.txt
    181C:
      image_group_id: I4885
      title: ''
      total_pages: 679
      order: 8
      base_file: 181C.txt
    155F:
      image_group_id: I4886
      title: ''
      total_pages: 840
      order: 9
      base_file: 155F.txt
    AAD9:
      image_group_id: I4887
      title: ''
      total_pages: 732
      order: 10
      base_file: AAD9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
